version: '3.7'

services:
  smurfs_image:
    build:
      context: .
      dockerfile: Dockerfile
      target: smurfs_image
    image: smurfs_image:latest
    volumes:
      - ./src/:/workspace
      - ./data/:/data
      - ./models:/models
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
    network_mode: host
    privileged: true
    container_name: smurfs_container
    runtime: nvidia
    environment:
      DISPLAY: ${DISPLAY}
      NAMESPACE: ${NAMESPACE}
    command: jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 --allow-root
    tty: true
    shm_size: 30gb